plugins {
    alias libs.plugins.android.dynamic.feature
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlin.ksp
}
android {
    namespace "com.centaury.cataloguemovie.favorite"
    compileSdkVersion AppConfig.ANDROID_COMPILE_SDK_VERSION

    buildFeatures {
        dataBinding true
        buildConfig true
    }

    defaultConfig {
        applicationId "com.centaury.cataloguemovie.favorite"
        minSdkVersion AppConfig.ANDROID_MIN_SDK_VERSION
        targetSdkVersion AppConfig.ANDROID_TARGET_SDK_VERSION
        versionCode AppConfig.ANDROID_VERSION_CODE
        versionName AppConfig.ANDROID_VERSION_NAME

        testInstrumentationRunner AppConfig.ANDROID_TEST_INSTRUMENTATION
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            debuggable true
        }
        buildTypes.each {
            it.buildConfigField("String", "IMAGE_URL", IMAGE_URL)
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }
}

dependencies {
    implementation project(":app")
    implementation project(AppConfig.PROJECT_DATA)
    implementation project(AppConfig.PROJECT_DOMAIN)
    implementation platform(libs.androidx.compose.bom)
    implementation libs.bundles.app
    ksp libs.bundles.kspApp
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.bundles.androidTestApp
}